# SIMPLEX PROJECTION

https://stanford.edu/~jduchi/projects/DuchiShSiCh08.pdf

In [2]:
import numpy as np

In [7]:
a = np.random.random(10)
print(a)

[0.41330133 0.42111514 0.97167815 0.30322349 0.55563783 0.84192529
 0.70321137 0.60737549 0.88059923 0.07859096]


In [15]:
u = np.sort(a)[::-1]
np.cumsum(u)

array([0.97167815, 1.85227739, 2.69420268, 3.39741405, 4.00478954,
       4.56042736, 4.9815425 , 5.39484383, 5.69806732, 5.77665828])

In [29]:
s = 1
n = len(a)
# get the array of cumulative sums of a sorted (decreasing) copy of v
u = np.sort(a)[::-1]
cssv = np.cumsum(u)
# get the number of > 0 components of the optimal solution
rho = np.nonzero(u * np.arange(1, n+1) > (cssv - s))[0][-1]
# compute the Lagrange multiplier associated to the simplex constraint
theta = float(cssv[rho] - s) / rho
# compute the projection by thresholding v using theta
w = (a - theta).clip(min=0)

In [31]:
w

array([0.        , 0.        , 0.22048077, 0.        , 0.        ,
       0.09072791, 0.        , 0.        , 0.12940185, 0.        ])

In [25]:
def simplex_proj(y):
    """ Projection of y onto simplex. """
    m = len(y)
    bget = False

    s = sorted(y, reverse=True)
    tmpsum = 0.

    for ii in range(m-1):
        tmpsum = tmpsum + s[ii]
        tmax = (tmpsum - 1) / (ii + 1);
        if tmax >= s[ii+1]:
            bget = True
            break

    if not bget:
        tmax = (tmpsum + s[m-1] -1)/m

    return np.maximum(y-tmax,0.)


In [28]:
simplex_proj(a)

array([0.        , 0.        , 0.37072025, 0.        , 0.        ,
       0.24096738, 0.10225346, 0.00641758, 0.27964133, 0.        ])

In [36]:
u.clip(min = 0)

array([0.97167815, 0.88059923, 0.84192529, 0.70321137, 0.60737549,
       0.55563783, 0.42111514, 0.41330133, 0.30322349, 0.07859096])